# config\ui_constants.py
import cv2 
DEBUG =False 
FFMPEG_LOG_FILE ="ffmpeg_log.txt"
RECORD_COLOR =(0 ,0 ,255 )
RECORD_DELAY_COLOR =(0 ,165 ,255 )
MOTION_COLOR =(0 ,255 ,0 )
RECTANGLE_WIDTH =70 
RECTANGLE_HEIGHT =70 
TEXT_PADDING_X =20 
TEXT_PADDING_Y =20 
FOCUS_CHECK_ENABLED =True 
WINDOW_NAME ="Live Preview"
WINDOW_RESOLUTION =(640 ,380 )
FONT =cv2 .FONT_HERSHEY_SIMPLEX 
DEFAULT_FONT_SCALE =1.5 
DEFAULT_TEXT_THICKNESS =2 
DEFAULT_BG_TEXT_THICKNESS =5 
DEFAULT_TEXT_COLOR =(255 ,255 ,255 )
DEFAULT_TEXT_BORDER_COLOR =(0 ,0 ,0 )
